# -*- coding: utf-8 -*-
"""Last Pencil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b622z0KDzwifhbiWg2RmXnklaTU8Dn4r
"""

import random

def get_numeric_input(prompt, error_message):
    while True:
        try:
            value = int(input(prompt))
            return value
        except ValueError:
            print(error_message)

def get_player_name():
    while True:
        player_name = input("Who will be the first (Ali, Mehmet):\n> ")
        if player_name.lower() in ['ali', 'mehmet']:
            return player_name
        else:
            print("Choose between 'Ali' and 'Mehmet'.")

def get_pencils_taken():
    while True:
        pencils_taken = input("Enter the number of pencils to take (1, 2, or 3):\n> ")
        if pencils_taken.isdigit() and int(pencils_taken) in [1, 2, 3]:
            return int(pencils_taken)
        else:
            print("Possible values: '1', '2' or '3'")

def bot_move(num_pencils):

    if (num_pencils - 1) % 4 == 0:
        return 3
    elif (num_pencils - 2) % 4 == 0:
        return 2
    elif (num_pencils - 3) % 4 == 0:
        return 1
    else:

        return random.randint(1, 3)


num_pencils = get_numeric_input("How many pencils would you like to use:\n> ", "The number of pencils should be numeric")


while num_pencils <= 0:
    print("The number of pencils should be positive")
    num_pencils = get_numeric_input("How many pencils would you like to use:\n> ", "The number of pencils should be numeric")


player1_name = get_player_name()


while num_pencils > 0:
    if player1_name.lower() == 'ali':

        print("Ali's turn:")


        pencils_taken = get_pencils_taken()
    else:

        print("Mehmet's turn:")


        pencils_taken = bot_move(num_pencils)


    while pencils_taken > num_pencils:
        print("Too many pencils were taken")
        pencils_taken = get_pencils_taken()


    num_pencils -= pencils_taken


    print("|" * num_pencils)


    if num_pencils == 0:
        break


    player1_name = 'Mehmet' if player1_name.lower() == 'ali' else 'Ali'


print(f"{player1_name} won!")