# -*- coding: utf-8 -*-
"""Simple Chat Bot with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KxYZxnBNzhgaKO288WnKEwXlKOWQd_ch
"""

from datetime import datetime


def get_current_year():
    return datetime.now().year


def greet_user():
    print(f"Hello! My name is Aid.")
    print(f"I was created in {get_current_year()}.")


def get_user_name():
    print("Please, remind me your name.")
    user_name = input()
    print(f"What a great name you have, {user_name}!")


def guess_user_age():
    print("Let me guess your age.")
    print("Enter remainders of dividing your age by 3, 5, and 7.")
    remainder3 = int(input())
    remainder5 = int(input())
    remainder7 = int(input())
    your_age = (remainder3 * 70 + remainder5 * 21 + remainder7 * 15) % 105
    print(f"Your age is {your_age}; that's a good time to start programming!")


def count_to_number():
    print("Now I will prove to you that I can count to any number you want.")
    count_limit = int(input())
    for i in range(count_limit + 1):
        print(f"{i} !")
    print("Completed, have a nice day!")


def programming_quiz():
    print("Let's test your programming knowledge.")
    print("Why do we use methods?")
    print("1. To repeat a statement multiple times.")
    print("2. To decompose a program into several small subroutines.")
    print("3. To determine the execution time of a program.")
    print("4. To interrupt the execution of a program.")


    correct_answer = "2"

    while True:
        user_answer = input("> ")

        if user_answer == correct_answer:
            print("Congratulations, have a nice day!")
            break
        else:
            print("Please, try again.")

# Main program
greet_user()
get_user_name()
guess_user_age()
count_to_number()
programming_quiz()