# -*- coding: utf-8 -*-
"""my_first_project_with_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_67WAd36LVz_areVgjsvutreiNg208s
"""

print("Prices:")
print("Bubblegum: $2")
print("Toffee: $0.2")
print("Ice cream: $5")
print("Milk chocolate: $4")
print("Doughnut: $2.5")
print("Pancake: $3.2")


print("\nEarned amount:")
bubblegum_earned = 202
toffee_earned = 118
ice_cream_earned = 2250
milk_chocolate_earned = 1680
doughnut_earned = 1075
pancake_earned = 80


print("Bubblegum: $" + str(bubblegum_earned))
print("Toffee: $" + str(toffee_earned))
print("Ice cream: $" + str(ice_cream_earned))
print("Milk chocolate: $" + str(milk_chocolate_earned))
print("Doughnut: $" + str(doughnut_earned))
print("Pancake: $" + str(pancake_earned))


total_income = bubblegum_earned + toffee_earned + ice_cream_earned + milk_chocolate_earned + doughnut_earned + pancake_earned
print("\nIncome: $" + str(total_income))


print("\nStaff expenses:")
staff_expenses = int(input("> "))


print("Other expenses:")
other_expenses = int(input("> "))


net_income = total_income - staff_expenses - other_expenses
print("\nNet income: $" + str(net_income))